// lib/components/Item/Item.tsx
import { SimpleCell } from "@vkontakte/vkui";
import { DataItem } from "../../../data";
import styles from "./Item.module.css";

export interface ItemProps extends DataItem {
  fill: string;
}

export function Item({ Icon, name, hint, text, link, fill }: ItemProps) {
  return (
    <SimpleCell
      before={<Icon fill={fill} width={28} height={28} aria-hidden />}
      multiline
      subtitle={text}
      href={link}
      target="_blank"
    >
      {name}
      {hint && <span className={styles.hint}>{" " + hint}</span>}
    </SimpleCell>
  );
}

// src/lib/Item.svelte
<script lang="ts">
	import { SimpleCell } from '@sveltevk/vksui';
	import type { DataItem } from '../data';

	export let item: DataItem;
	export let fill: string = undefined
</script>

<SimpleCell multiline description={item.text} href={item.link} target="_blank">
	<svelte:component this={item.icon} slot="before" {fill} width={28} height={28} />
	{item.name}
	{#if item.hint}
		<span style:color="var(--text_secondary)">
			{' ' + item.hint}
		</span>
	{/if}
</SimpleCell>
